# Generated by Django 4.2.25 on 2025-10-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('X_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
