# Generated by Django 5.2.7 on 2025-10-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X_app', '0002_comment_hashtag_invitationcode_invitelist_like_post_and_more'),
    ]

    operations = [
        # Content field already added manually - marking as no-op
        # migrations.AddField(
        #     model_name='post',
        #     name='content',
        #     field=models.TextField(blank=True, help_text='Legacy content field'),
        # ),
    ]
