# Generated by Django 5.2.7 on 2025-10-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X_app', '0003_post_content'),
    ]

    operations = [
        # Avatar field already added manually - marking as no-op
        # migrations.AddField(
        #     model_name='userprofile',
        #     name='avatar',
        #     field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/'),
        # ),
    ]
