# Generated by Django 4.2.25 on 2025-10-20 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('X_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='used_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('motivation_help_others', models.TextField()),
                ('human_nature_view', models.CharField(choices=[('unpredictable', 'People are unpredictable and complex'), ('environment', 'People are shaped by their environment'), ('inherently_good', 'People are inherently good'), ('self_interested', 'People are self-interested by nature')], max_length=100)),
                ('fairness_belief', models.CharField(choices=[('equal_outcomes', 'Fairness means equal outcomes for everyone'), ('equal_opportunities', 'Fairness means equal opportunities for everyone'), ('subjective', 'Fairness is subjective and context-dependent'), ('effort_merit', 'Fairness depends on effort and merit')], max_length=100)),
                ('long_term_goals', models.CharField(choices=[('security', 'Security and stability'), ('recognition', 'Recognition and status'), ('achievement', 'Need for personal achievement'), ('positive_impact', 'Desire to make a positive impact')], max_length=100)),
                ('response_personal_struggle', models.CharField(choices=[('emotional_support', 'I listen actively and offer emotional support'), ('practical_solutions', 'I try to provide practical solutions or advice'), ('share_experiences', "I share similar experiences I've had"), ('uncomfortable', 'I feel uncomfortable and change the subject')], max_length=100)),
                ('response_unfair_treatment', models.CharField(choices=[('speak_up', "Speak up immediately, even if it's uncomfortable"), ('assess_situation', 'Assess the situation and choose the right moment to intervene'), ('private_support', 'Support the person privately after the incident'), ('own_responsibilities', 'Focus on my own responsibilities and avoid involvement')], max_length=100)),
                ('success_definition', models.CharField(choices=[('financial_security', 'Achieving financial security and material comfort'), ('relationships', 'Building meaningful relationships and connections'), ('positive_impact', 'Making a positive impact on others and society'), ('personal_growth', 'Personal growth and self-actualization')], max_length=100)),
                ('forgiveness_role', models.CharField(choices=[('forgive_easily', "I forgive easily and don't hold grudges"), ('takes_time', 'I forgive but it takes time and effort'), ('difficult', 'I find it difficult to forgive serious betrayals'), ('situational', "Forgiveness depends on the situation and the person's remorse")], max_length=100)),
                ('coping_failure', models.CharField(choices=[('analyze_learn', 'I analyze what went wrong and learn from it'), ('seek_support', 'I seek support from friends or family'), ('process_emotions', 'I give myself time to process emotions'), ('dwell', 'I tend to dwell on it and find it hard to move forward')], max_length=100)),
                ('learning_cultures', models.CharField(choices=[('actively_curios', "I'm actively curious and seek out diverse experiences"), ('opportunities', 'I learn when opportunities present themselves'), ('stick_known', 'I prefer to stick to what I know and understand'), ('challenging', 'I find it challenging but recognize its importance')], max_length=100)),
                ('empathy_definition', models.CharField(blank=True, max_length=200)),
                ('values_conflict', models.CharField(blank=True, max_length=200)),
                ('help_motivation', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('invitation_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='X_app.invitationcode')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='questionnaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='X_app.questionnaireresponse'),
        ),
    ]
