# Generated by Django 5.2.7 on 2025-10-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X_app', '0004_userprofile_avatar'),
    ]

    operations = [
        # Content and avatar fields already added manually - marking as no-op
        # migrations.AddField(
        #     model_name='post',
        #     name='content',
        #     field=models.TextField(blank=True, help_text='Legacy content field'),
        # ),
        # migrations.AddField(
        #     model_name='userprofile',
        #     name='avatar',
        #     field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/'),
        # ),
    ]
