# Generated by Django 4.2.25 on 2025-10-20 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('X_app', '0004_invitationcode_used_by_alter_invitationcode_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
