# Generated by Django 4.2.25 on 2025-10-20 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('X_app', '0005_invitationcode_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='active_listening_definition',
            field=models.CharField(blank=True, choices=[('focus_speaker', 'Fully focusing on the speaker without distractions'), ('understand_words_emotions', 'Understanding both words and emotions being conveyed'), ('ask_questions', 'Asking clarifying questions to ensure comprehension'), ('remember_details', 'Remembering details for future reference'), ('all_above', 'All of the above')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='admit_fault_frequency',
            field=models.CharField(blank=True, choices=[('always', 'Always - accountability is important to me'), ('often', "Often - when I'm clearly in the wrong"), ('sometimes', 'Sometimes - depends on the situation'), ('rarely', 'Rarely - I find it difficult to admit mistakes'), ('never', 'Never - I prefer to avoid confrontation')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='boundaries_approach',
            field=models.CharField(blank=True, choices=[('clearly_communicate', 'I clearly communicate my limits and needs'), ('difficult_important', "I find it difficult but know it's important"), ('prioritize_others', "I tend to prioritize others' needs over mine"), ('set_feel_guilty', 'I set boundaries but feel guilty about it')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='change_mind_frequency',
            field=models.CharField(blank=True, choices=[('frequently', "Frequently - I'm open to new information"), ('sometimes', 'Sometimes - when presented with compelling evidence'), ('rarely', 'Rarely - I tend to stick to my initial decisions'), ('never', "Never - once I decide, that's it")], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='change_response',
            field=models.CharField(blank=True, choices=[('embrace_opportunity', 'I embrace it as an opportunity for new experiences'), ('adapt_gradually', 'I adapt gradually and give myself time'), ('resist_stability', 'I resist it and prefer stability'), ('reinvent_myself', 'I see it as a chance to reinvent myself')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='difficult_conversations',
            field=models.CharField(blank=True, choices=[('prepare_carefully', 'I prepare thoroughly and choose words carefully'), ('speak_from_heart', 'I speak from the heart and express emotions'), ('avoid_when_possible', 'I avoid them when possible'), ('address_directly', 'I address issues directly and honestly')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='emotion_processing',
            field=models.CharField(blank=True, choices=[('talk_trusted', 'I talk about them with trusted people'), ('write_journal', 'I write or journal about my feelings'), ('physical_activity', 'I engage in physical activity or hobbies'), ('suppress_later', 'I suppress them until I can deal with them later')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='emotional_intelligence_definition',
            field=models.CharField(blank=True, choices=[('aware_emotions', "Being aware of your own emotions and others'"), ('manage_effectively', 'Managing emotions effectively in difficult situations'), ('understand_dynamics', 'Understanding social dynamics and relationships'), ('guide_decisions', 'Using emotions to guide decision-making'), ('all_above_ei', 'All of the above')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='feedback_approach',
            field=models.CharField(blank=True, choices=[('give_constructive', 'I give constructive feedback thoughtfully'), ('receive_openly', 'I receive feedback openly and use it for growth'), ('giving_difficult', 'I find giving feedback difficult'), ('receiving_challenging', 'I find receiving feedback challenging')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='gratitude_role',
            field=models.CharField(blank=True, choices=[('regularly_express', 'I regularly express thanks for what I have'), ('notice_positive', "I notice positive aspects but don't always express it"), ('focus_lacking', "I focus more on what's lacking than what's present"), ('maintain_perspective', 'Gratitude helps me maintain perspective during challenges')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='home_concept',
            field=models.CharField(blank=True, choices=[('physical_place', 'A physical place where I live'), ('belonging_security', 'A feeling of belonging and security'), ('loved_ones', 'Where my loved ones are located'), ('state_of_mind', 'A state of mind rather than a location')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='human_being_definition',
            field=models.CharField(blank=True, choices=[('imperfect_learning', 'Being imperfect and learning from mistakes'), ('connect_emotionally', 'Connecting with others on an emotional level'), ('experience_emotions', 'Experiencing the full range of emotions'), ('seek_meaning', 'Seeking meaning and purpose in life'), ('all_above_human', 'All of the above')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='life_balance',
            field=models.CharField(blank=True, choices=[('equal_time', 'Equal time spent on work, relationships, and self-care'), ('harmony', 'Harmony between different aspects of life'), ('juggle_responsibilities', 'The ability to juggle multiple responsibilities'), ('know_priorities', 'Knowing when to prioritize different areas')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='life_meaning',
            field=models.CharField(blank=True, choices=[('career_success', 'Career achievements and professional success'), ('relationships', 'Relationships and connections with others'), ('personal_growth', 'Personal growth and self-discovery'), ('contribute_larger', 'Contributing to something larger than myself')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='most_authentic_feeling',
            field=models.CharField(blank=True, choices=[('when_alone', "When I'm alone and can be myself"), ('with_close_ones', "When I'm with close friends or family"), ('pursuing_passions', "When I'm pursuing my passions"), ('helping_others', "When I'm helping others"), ('being_creative', "When I'm being creative or expressive")], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='personal_growth_definition',
            field=models.CharField(blank=True, choices=[('learn_skills', 'Learning new skills and knowledge'), ('emotional_maturity', 'Developing emotional maturity'), ('better_relationships', 'Building better relationships'), ('overcome_challenges', 'Overcoming personal challenges'), ('continuous_improvement', 'Continuous self-improvement in all areas')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='self_love_level',
            field=models.CharField(blank=True, choices=[('completely_unconditionally', 'Yes, completely and unconditionally'), ('working_on_it', "Yes, but I'm still working on it"), ('sometimes', 'Sometimes, it depends on the day'), ('struggle', 'No, I struggle with self-acceptance'), ('not_sure', "I'm not sure what that means")], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='self_reflection_frequency',
            field=models.CharField(blank=True, choices=[('daily', "Daily - it's a regular practice for me"), ('weekly', 'Weekly - when I have time to think deeply'), ('occasionally', 'Occasionally - during significant life events'), ('rarely', 'Rarely - I prefer to stay busy and active'), ('never', "Never - I don't see the value in it")], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='stranger_interaction_motivation',
            field=models.CharField(blank=True, choices=[('right_thing', "It's the right thing to do"), ('inherent_worth', 'I believe in the inherent worth of all people'), ('positive_effects', 'Kindness creates positive ripple effects'), ('feel_good', 'It makes me feel good about myself'), ('all_above_stranger', 'All of the above')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='struggling_thoughts',
            field=models.CharField(blank=True, choices=[('want_to_help', '"I want to help them through this"'), ('learn_experience', '"I wonder what I can learn from their experience"'), ('feel_grateful', '"I feel grateful that I\'m not in their situation"'), ('feel_overwhelmed', '"I feel overwhelmed and unsure how to help"')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='true_happiness_knowledge',
            field=models.CharField(blank=True, choices=[('content_peace', 'I feel content and at peace with my life'), ('joy_everyday', 'I experience joy in everyday moments'), ('purpose_fulfillment', 'I have a sense of purpose and fulfillment'), ('express_gratitude', 'I can express gratitude for what I have'), ('all_above_happy', 'All of the above')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='trust_definition',
            field=models.CharField(blank=True, choices=[('reliability', 'Reliability and keeping promises'), ('emotional_safety', 'Emotional safety and vulnerability'), ('shared_values', 'Shared values and mutual respect'), ('time_consistency', 'Time and consistency in actions')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='uncertainty_response',
            field=models.CharField(blank=True, choices=[('gather_info', 'I gather information and make a plan'), ('seek_advice', 'I seek advice from trusted people'), ('feel_anxious', 'I feel anxious and prefer to avoid it'), ('embrace_growth', 'I embrace it as an opportunity for growth')], max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='vulnerability_strength',
            field=models.CharField(blank=True, choices=[('sign_true_strength', 'Vulnerability is a sign of true strength'), ('never_show', 'Strength means never showing vulnerability'), ('can_coexist', 'They can coexist - being strong includes being vulnerable'), ('makes_weak', "Vulnerability makes you weak in others' eyes")], max_length=100),
        ),
        migrations.CreateModel(
            name='UserCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.DecimalField(decimal_places=2, help_text='Compatibility score 0-100', max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('shared_empathy', models.BooleanField(default=False)),
                ('shared_growth', models.BooleanField(default=False)),
                ('shared_relationships', models.BooleanField(default=False)),
                ('shared_values', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['compatibility_score'], name='X_app_userc_compati_6017ff_idx'), models.Index(fields=['calculated_at'], name='X_app_userc_calcula_c52a12_idx')],
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
