# Generated by Django 5.2.7 on 2025-10-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X_app', '0006_post_content_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelist',
            name='secret_message',
            field=models.CharField(blank=True, help_text='Secret message included with the invitation', max_length=200),
        ),
    ]
