# Generated by Django 4.2.25 on 2025-10-21 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('X_app', '0006_questionnaireresponse_active_listening_definition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireresponse',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='last_name',
            field=models.CharField(default=0.00023515579071134625, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
