# Generated by Django 4.2.25 on 2025-10-21 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('X_app', '0007_model_reorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_profile', to='X_app.questionnaireresponse'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_name_profile', to='X_app.questionnaireresponse'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_name_profile', to='X_app.questionnaireresponse'),
        ),
    ]
