# Generated by Django 4.2.25 on 2025-10-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X_app', '0008_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='empathy_definition',
            field=models.CharField(choices=[('understanding', 'Understanding and sharing the feelings of others'), ('compassion', 'Feeling compassion and wanting to help'), ('perspective_taking', "Seeing things from another's perspective"), ('emotional_resonance', 'Feeling a deep emotional connection with others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='help_motivation',
            field=models.CharField(choices=[('intrinsic', 'I help others because it feels intrinsically rewarding'), ('extrinsic', 'I help others to gain recognition or rewards'), ('social', 'I help others to strengthen social bonds'), ('obligation', 'I help others out of a sense of duty')], max_length=200),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='motivation_help_others',
            field=models.CharField(choices=[('personal_growth', 'Personal growth and self-actualization'), ('helping_others', 'Helping others and making a difference'), ('financial_security', 'Achieving financial security'), ('social_status', 'Gaining social status and recognition')], max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='values_conflict',
            field=models.CharField(choices=[('open_dialogue', 'I engage in open dialogue to understand different perspectives'), ('avoid_conflict', 'I avoid conflict and try to keep the peace'), ('assertive', 'I assert my values while respecting others'), ('flexible', 'I adapt my values based on the situation')], max_length=200),
        ),
    ]
