# Generated by Django 4.2.25 on 2025-10-22 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('X_app', '0010_alter_userprofile_email_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_by_lists', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
