# Generated by Django 4.2.25 on 2025-10-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X_app', '0011_invitelist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitelist',
            options={'ordering': ['-invited_at']},
        ),
        migrations.AddIndex(
            model_name='invitelist',
            index=models.Index(fields=['inviter'], name='X_app_invit_inviter_541534_idx'),
        ),
        migrations.AddIndex(
            model_name='invitelist',
            index=models.Index(fields=['invitee'], name='X_app_invit_invitee_998b97_idx'),
        ),
    ]
