# Generated by Django 4.2.25 on 2025-10-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('X_app', '0012_alter_invitelist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitelist',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='invitelist',
            name='X_app_invit_inviter_541534_idx',
        ),
        migrations.RemoveIndex(
            model_name='invitelist',
            name='X_app_invit_invitee_998b97_idx',
        ),
        migrations.RemoveField(
            model_name='invitelist',
            name='invitee',
        ),
        migrations.AddField(
            model_name='invitelist',
            name='invite_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invite_lists', to='X_app.invitationcode'),
            preserve_default=False,
        ),
    ]
