# Generated by Django 4.2.25 on 2025-10-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X_app', '0013_alter_invitelist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelist',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
