# Generated by Django 4.2.25 on 2025-10-22 19:35

from django.db import migrations, models
import uuid


def populate_usernames(apps, schema_editor):
    """Populate unique usernames for existing QuestionnaireResponse records."""
    QuestionnaireResponse = apps.get_model('X_app', 'QuestionnaireResponse')
    
    for response in QuestionnaireResponse.objects.all():
        # Generate a unique username based on email and random suffix
        base_username = response.email.split('@')[0]
        unique_username = f"{base_username}_{uuid.uuid4().hex[:6]}"
        
        # Ensure uniqueness
        counter = 1
        original_username = unique_username
        while QuestionnaireResponse.objects.filter(username=unique_username).exists():
            unique_username = f"{original_username}_{counter}"
            counter += 1
        
        response.username = unique_username
        response.save()


class Migration(migrations.Migration):

    dependencies = [
        ('X_app', '0014_invitelist_email'),
    ]

    operations = [
        # Add the username field without unique constraint first
        migrations.AddField(
            model_name='questionnaireresponse',
            name='username',
            field=models.CharField(max_length=150, default='temp_username'),
        ),
        # Populate unique usernames
        migrations.RunPython(populate_usernames, reverse_code=migrations.RunPython.noop),
        # Add unique constraint
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
