# Generated by Django 4.2.25 on 2025-10-22 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('X_app', '0015_add_username_field'),
    ]

    operations = [
        # Manually add columns to existing X_app_post table
        migrations.RunSQL(
            """
            ALTER TABLE "X_app_post"
            ADD COLUMN IF NOT EXISTS caption TEXT DEFAULT '',
            ADD COLUMN IF NOT EXISTS image VARCHAR(100) NULL,
            ADD COLUMN IF NOT EXISTS video VARCHAR(100) NULL,
            ADD COLUMN IF NOT EXISTS privacy VARCHAR(10) DEFAULT 'public',
            ADD COLUMN IF NOT EXISTS location VARCHAR(255) DEFAULT '',
            ADD COLUMN IF NOT EXISTS likes_count INTEGER DEFAULT 0,
            ADD COLUMN IF NOT EXISTS comments_count INTEGER DEFAULT 0,
            ADD COLUMN IF NOT EXISTS shares_count INTEGER DEFAULT 0,
            ADD COLUMN IF NOT EXISTS views_count INTEGER DEFAULT 0,
            ADD COLUMN IF NOT EXISTS hashtags TEXT DEFAULT '',
            ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE,
            ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT FALSE;
            """,
            reverse_sql="""
            ALTER TABLE "X_app_post"
            DROP COLUMN IF EXISTS caption,
            DROP COLUMN IF EXISTS image,
            DROP COLUMN IF EXISTS video,
            DROP COLUMN IF EXISTS privacy,
            DROP COLUMN IF EXISTS location,
            DROP COLUMN IF EXISTS likes_count,
            DROP COLUMN IF EXISTS comments_count,
            DROP COLUMN IF EXISTS shares_count,
            DROP COLUMN IF EXISTS views_count,
            DROP COLUMN IF EXISTS hashtags,
            DROP COLUMN IF EXISTS is_featured,
            DROP COLUMN IF EXISTS is_archived;
            """
        ),
    ]
